version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - spring-hibernate-product-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://spring-hibernate-product-db:5432/spring_hibernate_product
      - SPRING_DATASOURCE_USERNAME=spring_hibernate_product
      - SPRING_DATASOURCE_PASSWORD=spring_hibernate_product

  spring-hibernate-product-db:
    image: postgres:14
    container_name: spring_hibernate_product_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=spring_hibernate_product
      - POSTGRES_USER=spring_hibernate_product
      - POSTGRES_DB=spring_hibernate_product

volumes:
  postgres_data:
